### ISSUE TITLE
Search box crushes an app

### ISSUE THREAD

**Issue by stanislawwitecki** [mickstar/Zoo-For-Zotero#113]
Hi,

Thank you for work! Zotero should have mobile app for a long time. 

I have an serious issue though. App crushes completaly when typing in search box. No letter is even showing there.

Best wishes,
Stanisław

**Comment by mickstar** [comment]
hmmm, could you tell me what kind of device you are using?

**Comment by stanislawwitecki** [comment]
Thanks for answer. I use Samusng Galaxy A41.

**Comment by JEStallings** [comment]
This may not be directly related to the above issue, but on my eink device (Onyx Nova 2), the instant search is impossibly slow. Offering a "disable instant search" setting might clear this up, instead of relying on the age of the firmware to disable. Everything else works perfectly—thanks so much for your work on this!

**Comment by mickstar** [comment]
Will add to the next release. Thanks for the suggestion.

**Comment by mickstar** [comment]
added in a043452b3bbdf481bf1f064a3e30236e61e6d279
