### ISSUE TITLE
Authors not sorted in item view/subtitle

### ISSUE THREAD

**Issue by mickstar** [mickstar/Zoo-For-Zotero#63]

**Comment by kavonjon** [comment]
Can confirm. This is now the most pressing issue for me, so I recommend it for triage. But I also want to clarify the issue to make sure we are describing the same thing:

The authors for each item are only sorted alphabetically, not in the order I defined and sorted them when using the desktop client. So when I attempt to sort my library by author, the items are sorted by the first author when sorted alphabetically, rather than by the true first author.

**Comment by mickstar** [comment]
thanks for clarifying, should be fixed in 6bd603bc7e4b5e05d0e889b4214ff0641e313c6d
and 7a23d336fd9907048c3de08b76792e95b226eaa7

**Comment by mickstar** [comment]
issue resolved in latest release (2.5).
Unfortunately you will need to clear app data and do a full refresh to actually see this change reflected.
