### ISSUE TITLE
Error on uploading changed pdf

### ISSUE THREAD

**Issue by yassendobrev** [mickstar/Zoo-For-Zotero#66]
Hi Mike, thanks for the awesome app!!

It works perfectly except for uploading edited pdfs. Every time I try to do this I get the error from the screenshot below and sometimes this corrupts the pdf on the server. I'm hosting my own WebDav server and it syncs ok both ways with 3 different Zotero Windows clients.

I also tried clearing the app data and setting up everything again, but it didn't help.

![Screenshot_20200411-190534](https://user-images.githubusercontent.com/60273197/79084253-91956c80-7ce7-11ea-8a21-288e83b1e490.jpg)

**Comment by mickstar** [comment]
hmm, strange. Sorry about the corruption. I can't think of how that might occur because it doesn't overwrite unless it has successfully transferred new files with a _NEW.zip suffix.

Here is the code that does attachment uploading, 
https://github.com/mickstar/Zoo-For-Zotero/blob/9e74322850f4db0f8e19e6ae410276ab73bb82a4/app/src/main/java/com/mickstarify/zooforzotero/ZoteroAPI/Webdav.kt#L115 

does it create WEFEWFE_NEW.zip and WEFEWFE_NEW.prop on your server?

Your error above seems related to a missing .prop file which is something the desktop zotero client creates to store metadata related to the attachments. Does that file exist on your server?

**Comment by yassendobrev** [comment]
Thanks for replying so fast and don't worry about the corrupted files! I really appreciate your effort.

Yes, it did create the **_NEW zip and prop file and it deleted the old zip and prop, which existed before the upload attempt. And the error isn't always 404, sometimes I also get "400 bad request" and then it's complaining that it can't find the _NEW.prop file.

**Comment by mickstar** [comment]
Sounds like the rename command isn't executing but the delete is. Does your
webdav server support renaming?

**Comment by yassendobrev** [comment]
You nailed it, the problem is indeed my server. Now I only need to figure out how to fix it, I'm using lighttpd on a raspberry pi. Thanks a lot!!

**Comment by mickstar** [comment]
When I get time I will try add some logic to stop the app from sending
delete requests if the rename failed. Thanks for the bug report!

**Comment by yassendobrev** [comment]
Switching for lighttpd to apache2 helped indeed. Now the app works perfectly, thanks!!
